<html>
    <head>
		<meta name="layout" content="main" />
    </head>
    <body>
        <h1 style="margin-left:20px;">SimpleCaptcha</h1>
        <div style="margin-left:20px;margin-bottom:20px;width:90%">Below are some images which have been generated by SimpleCaptcha. Reloading the page will yield new images. To see the code responsible for generating the CAPTCHA look at the source for the controller under <code>grails-app/controllers</code>.</div>
        <div class="dialog" style="margin-left:20px;width:60%;">
            <ul>
                <g:each var="c" in="${grailsApplication.controllerClasses}">
                    <g:if test="${!c.logicalPropertyName.contains('crack')}">
                        <li class="controller"><h1>${c.logicalPropertyName}Controller</h1><br/>
                        <g:each var="uri" in="${c.URIs}">
                            <g:if test="${uri.count('/') == 2 && !uri.endsWith('/') && !uri.endsWith('Bean')}">
                                <a href="${createLinkTo(file:uri)}"><img src="${createLinkTo(file:uri)}"> ${createLinkTo(file:uri)}</a><br />
                            </g:if>
                        </g:each>
                        </li>
                    </g:if>
                </g:each>
            </ul>
        </div>
    </body>
</html>
